homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin

############################# customize ###############################
  customize:
    switch.bett_links:
      friendly_name: Bettlampe
      icon: mdi:lightbulb
    switch.bett_rechts:
      friendly_name: Bettlicht
      icon: mdi:led-off
    switch.waschmaschine:
      friendly_name: Waschmaschine
#      icon: mdi:washing-machine
    switch.kaffeemaschine:
      friendly_name: Kaffeemaschine
      icon: mdi:coffee
    switch.wasserkocher:
      friendly_name: Wasserkocher
      icon: mdi:kettle
    switch.fire:
      friendly_name: Fire TV
      icon: mdi:play-circle
    binary_sensor.neo_coolcam_unknown_type0003_id0082_sensor_4_0:
      friendly_name: Staircase door
#      icon: mdi:play-circle
    binary_sensor.neo_coolcam_unknown_type0003_id0082_sensor_3_0:
      friendly_name: Balcony door
#      icon: mdi:play-circle
    sensor.neo_coolcam_unknown_type0003_id0082_access_control_3_9:
      friendly_name: Balcony door access control
    sensor.neo_coolcam_unknown_type0003_id0082_access_control_4_9:
      friendly_name: Staircase door acces control
    sensor.neo_coolcam_unknown_type0003_id0082_alarm_type_4_0:
      friendly_name: Staircase door alarm type
    sensor.neo_coolcam_unknown_type0003_id0082_alarm_level_4_1:
      friendly_name: Staircase door alaram level
    sensor.neo_coolcam_unknown_type0003_id0082_sourcenodeid_4_2:
      friendly_name: Staircase door node id
    sensor.neo_coolcam_unknown_type0003_id0082_alarm_type_3_0:
      friendly_name: Balcony door alarm type
    sensor.neo_coolcam_unknown_type0003_id0082_alarm_level_3_1:
      friendly_name: Balcony door alaram level
    sensor.neo_coolcam_unknown_type0003_id0082_sourcenodeid_3_2:
      friendly_name: Balcony door node id

group:
################ visenzews ###################
#  default_view:
#    view: yes
#    name: Home
#    entities:
#     - group.wohnzimmer
#     - group.schlafzimmer
#     - group.kueche
#     - group.badezimmer
#     - group.presenz
  wohnzimmer_view:
   view: yes
   name: Wohnzimmer
   entities:
    - group.wohnzimmer
  schlafzimmer_view:
    view: yes
    name: Schlafzimmer
    entities:
     - group.schlafzimmer
  kueche_view:
    view: yes
    name: Küche
    entities:
     - group.kueche
  badezimmer_view:
    view: yes
    name: Badezimmer
    entities:
     - group.badezimmer
  umgebung_view:
    view: yes
    name: Umgebung
    entities:
     - group.umgebung
  assistant_view:
    view: yes
    name: Assistant
    entities:
     - group.assistant
     - group.automations
     - switch.docker

############### gnroups ##################
  schlafzimmer:
    name: Schlafzimmer
    entities:
     - switch.bett_links
     - switch.bett_rechts
     - light.schlafzimmer_lampe
  wohnzimmer:
    name: Wohnzimmer
    entities:
     - switch.fire
     - light.stehlampe
     - light.wohnzimmer_lampe
     - media_player.video
     - scene.wohnzimmer_dunkel
     - scene.wohnzimmer_normal
     - camera.wohnzimmer_camera
  kueche:
    name: Küche
    entities:
     - switch.kaffeemaschine
     - switch.wasserkocher
  badezimmer:
    name: Badezimmer
    entities:
     - switch.waschmaschine
  assistant:
    name: Assistant
    entities:
     - sensor.cpu_speed
     - sensor.cpu_use
     - sensor.disk_use
     - sensor.disk_use_
     - sensor.disk_use_home
     - sensor.ipv4_address_eth0
     - sensor.packets_received_eth0
     - sensor.packets_sent_eth0
     - sensor.ram_free
     - sensor.since_last_boot
  umgebung:
    name: Umgebung
    entities:
     - sun.sun
     - sensor.yr_symbol
     - sensor.yr_cloudiness
     - sensor.yr_dewpoint_temperature
     - sensor.yr_fog
     - sensor.yr_high_clouds
     - sensor.yr_humidity
     - sensor.yr_low_clouds
     - sensor.yr_medium_clouds
     - sensor.yr_precipitation
     - sensor.yr_pressure
     - sensor.yr_temperature
     - sensor.yr_wind_direction
     - sensor.yr_wind_speed
  presenz:
    name: Presenz
    entities:
     - device_tracker.krassi
     - device_tracker.tab
  automations:
    name: Automation
    entities:
     - automation.media_player_playing
     - automation.media_player_pausedstopped
     - automation.update_notifications
     - automation.tab_at_home
     - automation.tab_not_at_home
     - automation.go_to_bed
  eingangstuer:
    name: Eingangstuer
    entities:
     - binary_sensor.neo_coolcam_unknown_type0003_id0082_sensor_4_0
     - sensor.neo_coolcam_unknown_type0003_id0082_access_control_4_9
     - sensor.neo_coolcam_unknown_type0003_id0082_alarm_type_4_0
     - sensor.neo_coolcam_unknown_type0003_id0082_alarm_level_4_1
     - sensor.neo_coolcam_unknown_type0003_id0082_sourcenodeid_4_2
  balkontuer:
    name: Balkontuer
    entities:
     - binary_sensor.neo_coolcam_unknown_type0003_id0082_sensor_3_0
     - sensor.neo_coolcam_unknown_type0003_id0082_access_control_3_9
     - sensor.neo_coolcam_unknown_type0003_id0082_alarm_type_3_0
     - sensor.neo_coolcam_unknown_type0003_id0082_alarm_level_3_1
     - sensor.neo_coolcam_unknown_type0003_id0082_sourcenodeid_3_2

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

######################## http server ###############################
http: !include http.yaml

#######################  zones  ####################################
zone: !include_dir_merge_list zones

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

recorder:
  purge_days: 3

# View all events in a logbook
logbook:

# Logger settings
#logger:
#  default: debug

# Track the sun
sun:

###  Sensors  ###
#  Sensors are anything (hardware or software) that has a state.
sensor: !include_dir_merge_list sensors

########################## media players ##########################
media_player: !include_dir_merge_list players

############################# trackers ############################
device_tracker: !include_dir_merge_list trackers

############################ emulated #############################
emulated_hue: !include emulated_hue.yaml

######################### notifications ###########################
notify: !include_dir_merge_list notifiers

############################# switches #################################
switch: !include_dir_merge_list switches

############################# scenes #################################
scene: !include_dir_merge_list scenes

############################# automations ###############################
automation player:
  - alias: "Media player paused/stopped"
    trigger:
      - platform: state
        entity_id: media_player.video
        from: 'playing'
    condition:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
    action:
        service: scene.turn_on
        entity_id: scene.Wohnzimmer_normal
  - alias: "Media player playing"
    trigger:
      - platform: state
        entity_id: media_player.video
        to: 'playing'
    condition:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
    action:
        service: scene.turn_on
        entity_id: scene.Wohnzimmer_dunkel

automation timer:
  alias: "Go to bed!"
  trigger:
    platform: time
    hours: 22
    minutes: 30
    seconds: 0
  action:
    service: notify.pushover
    data:
      message: 'Time to go to bed!'


automation hass_update:
  - alias: Update notifications
    trigger:
      - platform: state
        entity_id: updater.updater
    action:
      service: notify.pushover
      data:
        message: 'There is a new Home Assistant release available.'


automation nothome:
  alias: "Tab not at home"
  trigger:
    platform: state
    entity_id: device_tracker.Krassi
    # Optional
    from: 'home'
    to: 'not_home'

    # Alias for 'to'
    state: 'not_home'

  action:
    service: notify.pushover
    data:
      title: "Krassi is away"
      message: "Krassi has left home. Please come back soon. State: {{ states.device_tracker.Krassi.state }}"

automation home:
  alias: "Tab at home"
  trigger:
    platform: state
    entity_id: device_tracker.Krassi
    # Optional
    from: 'not_home'
    to: 'home'

    # Alias for 'to'
    state: 'home'

  action:
    service: notify.pushover
    data:
      title: "Krassi is home"
      message: "Welcome home, Krassi! Glad to see you again. State: {{ states.device_tracker.Krassi.state }}"

#automation door:
#  alias: "Staircase door"
#  trigger:
#    platform: event
#    event_type: zwave.node_event
#    event_data:
#      object_id: binary_sensor.__sensor_4_0
#     basic_level: 255
#  action:
#    service: notify.pushover
#    data:
#      title: "Staircase door"
#      message: "Staircase door changed state: {{ binary_sensor.__sensor_4_0.state }}"

automation staircase_door_closed:
  alias: "Staircase door closed"
  trigger:
    platform: state
    entity_id: binary_sensor.neo_coolcam_unknown_type0003_id0082_sensor_4_0
    from: 'on'
    to: 'off'
    state: 'off'

  action:
    service: notify.pushover
    data:
      title: "Staircase door closed"
      message: "Staircase door changed state (closed): {{  states.binary_sensor.neo_coolcam_unknown_type0003_id0082_sensor_4_0.state }}"

automation staircase_door_opened:
  alias: "Staircase door opened"
  trigger:
    platform: state
    entity_id: binary_sensor.neo_coolcam_unknown_type0003_id0082_sensor_4_0
    from: 'off'
    to: 'on'
    state: 'on'

  action:
    service: notify.pushover
    data:
      title: "Staircase door opened"
      message: "Staircase door changed state (opened): {{ states.binary_sensor.neo_coolcam_unknown_type0003_id0082_sensor_4_0.state }}"

automation balcony_door_closed:                
  alias: "Balcony door closed"                 
  trigger:                                       
    platform: state                              
    entity_id: binary_sensor.neo_coolcam_unknown_type0003_id0082_sensor_3_0                       
    from: 'on'                                   
    to: 'off'                                    
    state: 'off'                                 
                                                 
  action:                                        
    service: notify.pushover
    data:                                        
      title: "Balcony door closed"             
      message: "Balcony door changed state (closed): {{  states.binary_sensor.neo_coolcam_unknown_type0003_id0082_sensor_3_0.state }}"

automation balcony_door_opened:                
  alias: "Balcony door opened"                 
  trigger:                                       
    platform: state                              
    entity_id: binary_sensor.neo_coolcam_unknown_type0003_id0082_sensor_3_0                       
    from: 'off'                                  
    to: 'on'                                     
    state: 'on'                                  
                                                 
  action:                                        
    service: notify.pushover
    data:                                        
      title: "Balcony door opened"             
      message: "Balcony door changed state (opened): {{ states.binary_sensor.neo_coolcam_unknown_type0003_id0082_sensor_3_0.state }}"


############################# shell commands ###########################
#shell_command:
#  bash_turn_off: 'echo "off" > /tmp/cmd.txt'
#  bash_turn_on: 'echo "on" > /tmp/cmd.txt'

############################# cameras ##################################
camera: !include_dir_merge_list cameras 

############################# zwave ####################################
zwave: !include zwave.yaml

############################# mqtt #####################################
mqtt: !include mqtt.yaml

############################# weblinks #################################
weblink: !include weblink.yaml

############################# ifttt ####################################
ifttt: !include ifttt.yaml

automation ifttt_test:
  alias: Startup Notification
  trigger:
    platform: event
    event_type: homeassistant_start
  action:
    service: ifttt.trigger
    data: {"event":"HassStarted", "value1":"Hello World from Hass!"}

