homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin

############################# customize ###############################
  customize: !include_dir_merge_named customize

group: !include_dir_merge_named groups

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

######################## http server ###############################
http: !include http.yaml

#######################  zones  ####################################
zone: !include_dir_merge_list zones

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

recorder:
  purge_days: 3

# View all events in a logbook
logbook:

# Logger settings
#logger:
#  default: debug

# Track the sun
sun:

###  Sensors  ###
#  Sensors are anything (hardware or software) that has a state.
sensor: !include_dir_merge_list sensors

########################## media players ##########################
media_player: !include_dir_merge_list players

############################# trackers ############################
device_tracker: !include_dir_merge_list trackers

############################ emulated #############################
emulated_hue: !include emulated_hue.yaml

######################### notifications ###########################
notify: !include_dir_merge_list notifiers

############################# switches #################################
switch: !include_dir_merge_list switches

############################# scenes #################################
scene: !include_dir_merge_list scenes

############################# automations ###############################
automation: !include_dir_list automations

#automation door:
#  alias: "Staircase door"
#  trigger:
#    platform: event
#    event_type: zwave.node_event
#    event_data:
#      object_id: binary_sensor.__sensor_4_0
#     basic_level: 255
#  action:
#    service: notify.pushover
#    data:
#      title: "Staircase door"
#      message: "Staircase door changed state: {{ binary_sensor.__sensor_4_0.state }}"

############################# shell commands ###########################
#shell_command:
#  bash_turn_off: 'echo "off" > /tmp/cmd.txt'
#  bash_turn_on: 'echo "on" > /tmp/cmd.txt'

############################# cameras ##################################
camera: !include_dir_merge_list cameras 

############################# zwave ####################################
zwave: !include zwave.yaml

############################# mqtt #####################################
mqtt: !include mqtt.yaml

############################# weblinks #################################
weblink: !include weblink.yaml

############################# ifttt ####################################
ifttt: !include ifttt.yaml

