homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin

  # Customize - names, icons
  customize: !include_dir_merge_named customize

# Groups and views
group: !include_dir_merge_named groups

# Enables the frontend
frontend:

# http server
http: !include http.yaml

# Zones
zone: !include_dir_merge_list zones

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# Records events
recorder: !include recorder.yaml

# View all events in a logbook
logbook:

# Logger settings
logger: !include logger.yaml

# Weblink
weblink: !include weblink.yaml

# Track the sun
sun:

# Sensors
sensor: !include_dir_merge_list sensors

# Media players 
media_player: !include_dir_merge_list players

# Trackers
device_tracker: !include_dir_merge_list trackers

# Emulated hue 
emulated_hue: !include emulated_hue.yaml

# Notifications 
notify: !include_dir_merge_list notifiers

# Switches
switch: !include_dir_merge_list switches

# Scenes
scene: !include_dir_merge_list scenes

# Shell command
shell_command: !include shell_command.yaml

# Automations
automation: !include_dir_list automations

# Cameras
camera: !include_dir_merge_list cameras 

# Z-Wave
zwave: !include zwave.yaml

# MQTT
mqtt: !include mqtt.yaml

# IFTT
ifttt: !include ifttt.yaml

# xiaomi
xiaomi: !include xiaomi.yaml

#######################################################
# Testing stuff

#automation door:
#  alias: "Staircase door"
#  trigger:
#    platform: event
#    event_type: zwave.node_event
#    event_data:
#      object_id: binary_sensor.__sensor_4_0
#     basic_level: 255
#  action:
#    service: notify.pushover
#    data:
#      title: "Staircase door"
#      message: "Staircase door changed state: {{ binary_sensor.__sensor_4_0.state }}"

