  umgebung:
    name: Umgebung
    entities:
     - sun.sun
     - sensor.yr_symbol
     - sensor.yr_cloudiness
     - sensor.yr_dewpoint_temperature
     - sensor.yr_fog
     - sensor.yr_high_clouds
     - sensor.yr_humidity
     - sensor.yr_low_clouds
     - sensor.yr_medium_clouds
     - sensor.yr_precipitation
     - sensor.yr_pressure
     - sensor.yr_temperature
     - sensor.yr_wind_direction
     - sensor.yr_wind_speed
