homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 49.5820216
  longitude: 10.9967316
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 226
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  api_password: Slon4e,.Slon4e,.

logger:
  default: warn

# Checks for available updates
#updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time.
#history:

# View all events in a logbook
#logbook:

# Track the sun
#sun:

#media_player:
# - platform: frontier_silicon
#   host: 192.168.1.180

# My config
#media_player:
#  platform: kodi
#  host: http://172.17.0.1
#  name: kodi
#  username: kodi
#  password: kodi
#  port: 8080
#
#device_tracker tab:
#  platform: nmap_tracker
#  hosts: 192.168.1.237
##  home_interval: 10
#
#device_tracker s7:
#  platform: nmap_tracker
#  hosts: 192.168.1.62
##  home_interval: 10

#media_player kitchen:
#  platform: dlna 
#  host: 192.168.1.28

# 167 - fire tv
